#!/usr/bin/env sh
PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
set -e

# Get the variables
source /scripts/env

## Qmail installation Based on LWQ ##
mkdir /usr/src ${QMAIL_HOME} && cd /usr/src
curl ${QMAIL_DL_URL} -o netqmail-1.06.tar.gz
curl ${CHANNEL_PATCH_URL} -o netqmail-1.06-channels.patch
curl ${BIG_DNS_PATCH_URL} -o qmail-103.patch
curl ${CNAME_PATCH} -o any-to-cname.patch
tar zxf netqmail-1.06.tar.gz
cd netqmail-1.06
patch < ../netqmail-1.06-channels.patch
patch < ../qmail-103.patch
patch < ../any-to-cname.patch
sed -i -e 's#^22#8#g' conf-channels

adduser qmaild -g nofiles -h ${QMAIL_HOME} -s /sbin/nologin -D
adduser alias -g nofiles -h ${QMAIL_HOME}/alias -s /sbin/nologin -D
adduser qmaill -g nofiles -h ${QMAIL_HOME} -s /sbin/nologin -D
adduser qmailp -g nofiles -h ${QMAIL_HOME} -s /sbin/nologin -D
addgroup qmail
adduser qmailq -g qmail -h ${QMAIL_HOME} -s /sbin/nologin -D
adduser qmailr -g qmail -h ${QMAIL_HOME} -s /sbin/nologin -D
adduser qmails -g qmail -h ${QMAIL_HOME} -s /sbin/nologin -D

make setup check

cd /usr/src/
curl ${UCSPI_DL_URL} -o ucspi-tcp-0.88.tar.gz
tar zxf ucspi-tcp-0.88.tar.gz
cd ucspi-tcp-0.88/
patch < /usr/src/netqmail-1.06/other-patches/ucspi-tcp-0.88.errno.patch
make && make setup check

cd /usr/src
curl ${DAEMONTOOLS_DL_URL} -o daemontools-0.76.tar.gz
mkdir /package
mv daemontools-0.76.tar.gz /package/
cd /package/
tar xvfz daemontools-0.76.tar.gz
rm -f daemontools-0.76.tar.gz
cd admin/daemontools-0.76/src
patch < /usr/src/netqmail-1.06/other-patches/daemontools-0.76.errno.patch
cd /package/admin/daemontools-0.76/
package/install

cat > ${QMAIL_HOME}/rc <<EOF
#!/bin/sh

# Using stdout for logging
# Using control/defaultdelivery from qmail-local to deliver messages by default

exec env - PATH="${QMAIL_HOME}/bin:\$PATH" \
qmail-start "\`cat ${QMAIL_HOME}/control/defaultdelivery\`"
EOF

chmod 755 ${QMAIL_HOME}/rc
mkdir ${QMAIL_LOG_DIR}
echo "./Maildir" > ${QMAIL_HOME}/control/defaultdelivery
echo "mx01.domain.local" > ${QMAIL_HOME}/control/me
echo "mx01.domain.local" > ${QMAIL_HOME}/control/locals
echo "mx01.domain.local" > ${QMAIL_HOME}/control/rcpthosts


cat > /var/qmail/bin/qmailctl <<EOF
#!/bin/sh

# description: the qmail MTA

PATH=/var/qmail/bin:/bin:/usr/bin:/usr/local/bin:/usr/local/sbin
export PATH

QMAILDUID=\`id -u qmaild\`
NOFILESGID=\`id -g qmaild\`

case \$1 in
  start)
    echo "Starting qmail"
    if svok /service/qmail-send ; then
      svc -u /service/qmail-send /service/qmail-send/log
    else
      echo "qmail-send supervise not running"
    fi
    if svok /service/qmail-smtpd ; then
      svc -u /service/qmail-smtpd /service/qmail-smtpd/log
    else
      echo "qmail-smtpd supervise not running"
    fi
    if [ -d /var/lock/subsys ]; then
      touch /var/lock/subsys/qmail
    fi
    ;;
  stop)
    echo "Stopping qmail..."
    echo "  qmail-smtpd"
    svc -d /service/qmail-smtpd /service/qmail-smtpd/log
    echo "  qmail-send"
    svc -d /service/qmail-send /service/qmail-send/log
    if [ -f /var/lock/subsys/qmail ]; then
      rm /var/lock/subsys/qmail
    fi
    ;;
  stat)
    svstat /service/qmail-send
    svstat /service/qmail-send/log
    svstat /service/qmail-smtpd
    svstat /service/qmail-smtpd/log
    echo "QUEUE STATUS"
    qmail-qstat
    echo "" && echo -n "Microsoft "
    qmail-qstat0
    echo -n "Yahoo "
    qmail-qstat1
    echo -n "Gmail "
    qmail-qstat2
    echo ""
    ;;
  doqueue|alrm|flush)
    echo "Flushing timeout table and sending ALRM signal to qmail-send."
    /var/qmail/bin/qmail-tcpok
    svc -a /service/qmail-send
    ;;
  queue)
    qmail-qstat
    qmail-qread
    ;;
  queue-microsoft)
    qmail-qread0
    ;;
  queue-yahoo)
    qmail-qread1
    ;;
  queue-gmail)
    qmail-qread2
    ;;
  reload|hup)
    echo "Sending HUP signal to qmail-send."
    svc -h /service/qmail-send
    ;;
  pause)
    echo "Pausing qmail-send"
    svc -p /service/qmail-send
    echo "Pausing qmail-smtpd"
    svc -p /service/qmail-smtpd
    ;;
  cont)
    echo "Continuing qmail-send"
    svc -c /service/qmail-send
    echo "Continuing qmail-smtpd"
    svc -c /service/qmail-smtpd
    ;;
  restart)
    echo "Restarting qmail:"
    echo "* Stopping qmail-smtpd."
    svc -d /service/qmail-smtpd /service/qmail-smtpd/log
    echo "* Sending qmail-send SIGTERM and restarting."
    svc -t /service/qmail-send /service/qmail-send/log
    echo "* Restarting qmail-smtpd."
    svc -u /service/qmail-smtpd /service/qmail-smtpd/log
    ;;
  cdb)
    tcprules /etc/tcp.smtp.cdb /etc/tcp.smtp.tmp < /etc/tcp.smtp
    chmod 644 /etc/tcp.smtp.cdb
    echo "Reloaded /etc/tcp.smtp."
    ;;
  help)
    cat <<HELP
   stop -- stops mail service (smtp connections refused, nothing goes out)
  start -- starts mail service (smtp connection accepted, mail can go out)
  pause -- temporarily stops mail service (connections accepted, nothing leaves)
   cont -- continues paused mail service
   stat -- displays status of mail service
    cdb -- rebuild the tcpserver cdb file for smtp
restart -- stops and restarts smtp, sends qmail-send a TERM & restarts it
doqueue -- schedules queued messages for immediate delivery
 reload -- sends qmail-send HUP, rereading locals and virtualdomains
  queue -- shows status of queue
   alrm -- same as doqueue
  flush -- same as doqueue
    hup -- same as reload
HELP
    ;;
  *)
    echo "Usage: \$0 {start|stop|restart|doqueue|flush|reload|stat|pause|cont|cdb|queue|help}"
    exit 1
    ;;
esac

exit 0
EOF

chmod 755 ${QMAIL_HOME}/bin/qmailctl
ln -s ${QMAIL_HOME}/bin/qmailctl /usr/bin

mkdir -p ${QMAIL_HOME}/supervise/qmail-send
mkdir -p ${QMAIL_HOME}/supervise/qmail-smtpd
mkdir -p ${QMAIL_HOME}/supervise/qmail-send/log
mkdir -p ${QMAIL_HOME}/supervise/qmail-smtpd/log

cat > ${QMAIL_HOME}/supervise/qmail-send/run <<EOF
#!/bin/sh
exec ${QMAIL_HOME}/rc
EOF

cat > ${QMAIL_HOME}/supervise/qmail-send/log/run <<EOF
#!/bin/sh
exec /usr/local/bin/setuidgid qmaill /usr/local/bin/multilog t ${QMAIL_LOG_DIR}
EOF

cat > ${QMAIL_HOME}/supervise/qmail-smtpd/run <<EOF
#!/bin/sh

QMAILDUID=\`id -u qmaild\`
NOFILESGID=\`id -g qmaild\`
MAXSMTPD=\`cat ${QMAIL_HOME}/control/concurrencyincoming\`
LOCAL=\`head -1 ${QMAIL_HOME}/control/me\`

if [ -z "\$QMAILDUID" -o -z "\$NOFILESGID" -o -z "\$MAXSMTPD" -o -z "\$LOCAL" ]; then
    echo QMAILDUID, NOFILESGID, MAXSMTPD, or LOCAL is unset in
    echo ${QMAIL_HOME}/supervise/qmail-smtpd/run
    exit 1
fi

if [ ! -f ${QMAIL_HOME}/control/rcpthosts ]; then
    echo "No ${QMAIL_HOME}/control/rcpthosts!"
    echo "Refusing to start SMTP listener because it'll create an open relay"
    exit 1
fi
exec /usr/local/bin/tcpserver -v -R -l "\$LOCAL" -x /etc/tcp.smtp.cdb -c "\$MAXSMTPD" \
-u "\$QMAILDUID" -g "\$NOFILESGID" 0 smtp ${QMAIL_HOME}/bin/qmail-smtpd 2>&1
EOF


cat > ${QMAIL_HOME}/supervise/qmail-smtpd/log/run <<EOF
#!/bin/sh
exec /usr/local/bin/setuidgid qmaill /usr/local/bin/multilog t ${QMAIL_LOG_DIR}/smtpd
EOF

chmod 755 ${QMAIL_HOME}/supervise/qmail-send/run
chmod 755 ${QMAIL_HOME}/supervise/qmail-send/log/run
chmod 755 ${QMAIL_HOME}/supervise/qmail-smtpd/run
chmod 755 ${QMAIL_HOME}/supervise/qmail-smtpd/log/run

mkdir -p /var/log/qmail/smtpd
chown qmaill /var/log/qmail /var/log/qmail/smtpd

ln -s /var/qmail/supervise/qmail-send /var/qmail/supervise/qmail-smtpd /service

cat > /etc/tcp.smtp <<EOF
127.:allow,RELAYCLIENT=""
172.17.:allow,RELAYCLIENT=""
EOF
tcprules /etc/tcp.smtp.cdb /etc/tcp.smtp.tmp < /etc/tcp.smtp
chmod 644 /etc/tcp.smtp.cdb

# Channel patch configuration

cat > /var/qmail/control/suppls0 <<EOF
bing.com
bing.net
bing.co.uk
bing.co
bingbar.com
bingbar.net
bingtoolbar.com
hotmail.com
hotmail.co.uk
hotmail.eu
hotmail.co
hotmail.net
hotmail.org
live.com
live.co.uk
live.net
live.co
live.org
live.eu
internetexplorer.com
internetexplorer.co
ie8.co
ie9.com
ie10.com
ie11.com
mepn.com
microsoft.com
msdn.com
microsoftsilverlight.com
microsoftsilverlight.org
microsoftsilverlight.net
microsoftsqlserver.com
sqlserver.net
microsoftvisualstudio.com
microsoftvisualstudio.net
visualstudio.com
visualstudio.co.uk
visualstudio.net
visualstudio.eu
visualstudio.co
skydrive.com
skydrive.co
onedrive.com
onedrive.co.uk
onedrive.net
onedrive.org
onedrive.co
onedrive.eu
1drv.ms
skype.com
skype.org
skype.net
skype.co.uk
skype.co
skype.eu
outlook.com
outlook.org
outlook.co
outlook.eu
windowsmobile.com
windowsmobile.co.uk
windowsmobile.org
windowsmobile.co
windowsmobile.eu
windowsphone.com
windowsphone.co.uk
windowsphone.org
windowsphone.co
windowsphone.net
zune.com
zune.co.uk
zune.org
zune.net
zune.co
zune.eu
xbox.com
xbox.co.uk
xbox.org
xbox.co
xbox.eu
xbox360.com
xbox360.co.uk
xbox360.co
xbox360.eu
xbox360.org
xboxone.com
xboxone.co.uk
xboxone.co
xboxone.eu
office.com
microsoftonline.com
microsoft.com
microsoft.org
microsoft.net
microsoft.co.uk
microsoft.co
microsoft.nl
microsoft.it
outlook.it
skype.it
live.it
hotmail.it
microsoft.de
outlook.de
skype.de
live.de
hotmail.de
microsoft.fr
outlook.fr
skype.fr
live.fr
hotmail.fr
microsoft.dk
outlook.dk
skype.dk
live.dk
hotmail.dk
outlook.com.au
EOF

cat > /var/qmail/control/suppls1 <<EOF
yahoo.com
yahoo.com.tr
yahoo.co.uk
yahoo.co.jp
yahoo.co.kr
yahoo.co.id
yahoo.co.in
yahoo.com.sg
yahoo.com.ph
EOF


cat > /var/qmail/control/suppls2 <<EOF
gmail.com
googlemail.com
EOF

echo "100" > ${QMAIL_HOME}/control/concurrencyincoming
echo "50" > ${QMAIL_HOME}/control/concurrencyremote
echo "5" > ${QMAIL_HOME}/control/concurrencysuppl0
echo "10" > ${QMAIL_HOME}/control/concurrencysuppl1
echo "10" > ${QMAIL_HOME}/control/concurrencysuppl2
chmod 644 ${QMAIL_HOME}/control/concurrency*
chmod 644 ${QMAIL_HOME}/control/suppls*

cat > ${QMAIL_HOME}/bin/qmail-qstat0 <<EOF
#!/bin/sh
cd ${QMAIL_HOME}
messdirs=\`echo queue/suppl0/* | wc -w\`
messfiles=\`find queue/suppl0/* -print | wc -w\`
echo messages in queue: \`expr \$messfiles - \$messdirs\`
EOF

cat > ${QMAIL_HOME}/bin/qmail-qstat1 <<EOF
#!/bin/sh
cd ${QMAIL_HOME}
messdirs=\`echo queue/suppl1/* | wc -w\`
messfiles=\`find queue/suppl1/* -print | wc -w\`
echo messages in queue: \`expr \$messfiles - \$messdirs\`
EOF

cat > ${QMAIL_HOME}/bin/qmail-qstat2 <<EOF
#!/bin/sh
cd ${QMAIL_HOME}
messdirs=\`echo queue/suppl2/* | wc -w\`
messfiles=\`find queue/suppl2/* -print | wc -w\`
echo messages in queue: \`expr \$messfiles - \$messdirs\`
EOF

cat > ${QMAIL_HOME}/bin/qmail-qread0 <<EOF
#!/bin/sh
# MS qread
for i in \`egrep -ir "hotmail|outlook|live.c|windows|" /var/qmail/queue/suppl0/*\`; do
	remote=\`echo $i |sed 's#:T# #g' |awk '{print $2}'\`
	info=\`echo $i |sed 's#:T# #g' |awk '{print $1}' |sed 's#/suppl0/#/info/#g'\`
	sender=\`cat $info\`
	echo From: "$sender" To: "$remote" |sed 's#: F#: #'
done
EOF

cat > ${QMAIL_HOME}/bin/qmail-qread1 <<EOF
#!/bin/sh
# Yahoo qread
for i in \`egrep -ir yahoo /var/qmail/queue/suppl1/*\`; do
	remote=\`echo $i |sed 's#:T# #g' |awk '{print $2}'\`
	info=\`echo $i |sed 's#:T# #g' |awk '{print $1}' |sed 's#/suppl1/#/info/#g'\`
	sender=\`cat $info\`
	echo From: "$sender" To: "$remote" |sed 's#: F#: #'
done
EOF

cat > ${QMAIL_HOME}/bin/qmail-qread2 <<EOF
#!/bin/sh
# Google qread
for i in \`egrep -ir "google|gmail"/var/qmail/queue/suppl2/*\`; do
	remote=\`echo $i |sed 's#:T# #g' |awk '{print $2}'\`
	info=\`echo $i |sed 's#:T# #g' |awk '{print $1}' |sed 's#/suppl2/#/info/#g'\`
	sender=\`cat $info\`
	echo From: "$sender" To: "$remote" |sed 's#: F#: #'
done
EOF

cd ${QMAIL_HOME}/bin
chmod +x qmail-qstat* && chmod +x ${QMAIL_HOME}/bin/qmail-qread*

ln -s /scripts/qmail-configurator /usr/bin/qmail-configurator
sh /scripts/dkim-setup
cd ~