#!/usr/bin/env sh
PATH=/bin:/usr/bin:/usr/local/bin

source /scripts/env

case "$1" in
  set-fqdn)
      FQDN="$2"
      if [[ -n "$FQDN" ]]; then
          VALIDFQDN='^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$';
          if echo "$FQDN" |egrep -q "$VALIDFQDN"; then
              echo "$FQDN" | tee ${QMAIL_HOME}/control/me ${QMAIL_HOME}/control/locals ${QMAIL_HOME}/control/rcpthosts >/dev/null
              qmailctl restart
          else
              echo -e "You need to enter a valid hostname, domain or FQDN."
              echo -e "NOTE: The best option is providing FQDN with a valid A and PTR record to gain better reputation from important vendors like gmail.com."
              exit 1
          fi
      else
          echo -e "You need to enter a hostname, domain or FQDN."
          echo -e "NOTE: The best option is providing FQDN with a valid A and PTR record to gain better reputation from important email like gmail.com."
          exit 1
      fi
      ;;
  relayclient)
      IPRANGE="$2"
      if [[ -n "$IPRANGE" ]]; then
          VALIDIPRANGE='(^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$|^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){1,3}$)';
          if echo "$IPRANGE" |egrep -q "$VALIDIPRANGE"; then
              echo "$IPRANGE":allow,RELAYCLIENT=\"\" >> /etc/tcp.smtp
              qmailctl cdb
              echo "Relay has been granted for "$IPRANGE""
          else
              echo -e "You need to enter a valid IP or IP range for tcp.smtp relayclient."
              echo -e "To specify a single IP addess: 1.2.3.4"
              echo -e "And for a subnet: 1.2.3. or 1.2. etc."
              exit 1
          fi
      else
          echo -e "You need to enter an IP or IP range for tcp.smtp relayclient."
          echo -e "To specify a single IP addess: 1.2.3.4"
          echo -e "And for a subnet: 1.2.3. or 1.2. etc."
          exit 1
      fi
      ;;
  throttle)
      THROTTLEDOMAIN="$2"
      CONCURRENTLIMIT="$3"
      if [[ -n "$THROTTLEDOMAIN" ]]; then

          echo "$THROTTLEDOMAIN"
          echo "$CONCURRENTLIMIT"
      else
          echo -e "You need to enter an IP or IP range for tcp.smtp relayclient."
          echo -e "To specify a single IP addess: 1.2.3.4"
          echo -e "And for a subnet: 1.2.3. or 1.2. etc."
          exit 1
      fi
      ;;
  *)
      echo $"Usage: "$0" {set-fqdn|relayclient}"
      exit 1
esac